enum WindowsChannels {
    'GET_CONFIRMATIONS_WINDOW_PARMAS'='GET_CONFIRMATIONS_WINDOW_PARAMS',
    'OPEN_CONFIRMATIONS_WINDOW'='OPEN_CONFIRMATIONS_WINDOW',
    'CLOSE_CONFIRMATIONS_WINDOW'='CLOSE_CONFIRMATIONS_WINDOW',
    'MAXIMIZE_CONFIRMATIONS_WINDOW'='MAXIMIZE_CONFIRMATIONS_WINDOW',
    'MINIMIZE_CONFIRMATIONS_WINDOW'='MINIMIZE_CONFIRMATIONS_WINDOW',
    'CENTERIZE_CONFIRMATIONS_WINDOW'='CENTERIZE_CONFIRMATIONS_WINDOW',

    'GET_PROFILE_PARAMS'='GET_PROFILE_PARAMS',
    'OPEN_MAIN_WINDOW'='OPEN_MAIN_WINDOW',
    'CLOSE_MAIN_WINDOW'='CLOSE_MAIN_WINDOW',
    'MAXIMIZE_MAIN_WINDOW'='MAXIMIZE_MAIN_WINDOW',
    'MINIMIZE_MAIN_WINDOW'='MINIMIZE_MAIN_WINDOW',
    'CENTERIZE_MAIN_WINDOW'='CENTERIZE_MAIN_WINDOW',
    'GET_MAXIMIZE_STATUS_MAIN_WINDOW' = 'GET_MAXIMIZE_STATUS_MAIN_WINDOW',

    'GET_ASK_WINDOW_PARAMS'='GET_ASK_WINDOW_PARAMS',
    'OPEN_ASK_WINDOW'='OPEN_ASK_WINDOW',
    'CLOSE_ASK_WINDOW'='CLOSE_ASK_WINDOW',
    'MAXIMIZE_ASK_WINDOW'='MAXIMIZE_ASK_WINDOW',
    'MINIMIZE_ASK_WINDOW'='MINIMIZE_ASK_WINDOW',
    'CENTERIZE_ASK_WINDOW'='CENTERIZE_ASK_WINDOW',

    'OPEN_AUTH_WINDOW'='OPEN_AUTH_WINDOW',
    'CLOSE_AUTH_WINDOW'='CLOSE_AUTH_WINDOW',
    'MAXIMIZE_AUTH_WINDOW'='MAXIMIZE_AUTH_WINDOW',
    'MINIMIZE_AUTH_WINDOW'='MINIMIZE_AUTH_WINDOW',
    'CENTERIZE_AUTH_WINDOW'='CENTERIZE_AUTH_WINDOW',

    'OPEN_ERROR_WINDOW'='OPEN_ERROR_WINDOW',
    'CLOSE_ERROR_WINDOW'='CLOSE_ERROR_WINDOW',
    'MAXIMIZE_ERROR_WINDOW'='MAXIMIZE_ERROR_WINDOW',
    'MINIMIZE_ERROR_WINDOW'='MINIMIZE_ERROR_WINDOW',
    'CENTERIZE_ERROR_WINDOW'='CENTERIZE_ERROR_WINDOW',
    'GET_ERROR_WINDOW_PARAMS'='GET_ERROR_WINDOW_PARAMS',
    'GET_SECRET_KEY' = 'GET_SECRET_KEY',
    'SET_SECRET_KEY' = 'SET_SECRET_KEY'
}

export default WindowsChannels;