enum AvalibleFieldTypes {
    checkbox = "checkbox",
    number = "number",
    profileName="profileName",
    profileAvatar="profileAvatar",
    ktState = "ktState",
    tpState = "tpState",
    tradeState = "tradeState",
    tmApiKey = "tmApiKey",
    startButton = "startButton",
    steamAccountAvatar = "steamAccountAvatar",
    steamAccountButtons = "steamAccountButtons",
    steamAccountNickname = "steamAccountNickname",
    steamAccountLevel = "steamAccountLevel",
    steamAccountBalance = "steamAccountBalance",
    csgoTmBalance = "csgoTmBalance",
    steamAccountName = "steamAccountName",
    steamPassword = "steamPassword",
    steamGuard = "steamGuard",
    mail = "mail",
    mailPassword = "mailPassword",
    refreshButton = "refreshButton",
    exportButton = "exportButton",
    editingButton = "editingButton",
    deleteButton = "deleteButton",
    miniProxy = "miniProxy",
    proxyUsername = "proxyUsername",
    proxyPassword = "proxyPassword",
    proxyHost = "proxyHost",
    proxyPort = "proxyPort",
    linkedSteamAccounts = "linkedSteamAccounts",
    linkedProfiles = "linkedProfiles",
    linkedProxies = "linkedProxies",
    testProxyButton = "testProxyButton",
    chromeStartButton = "chromeStartButton",
    
}

export default AvalibleFieldTypes;